# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: leoaguia <leoaguia@student.42porto.com>    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2026/09/01 02:30:07 by leoaguia          #+#    #+#              #
#    Updated: 2026/09/01 18:50:00 by leoaguia         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Makefile

NAME     := ircserv

CXX      := c++

CXXFLAGS := -Wall -Wextra -Werror -std=c++98

INCDIR   := inc
SRCDIR   := src
OBJDIR   := obj

# Use find so we don't have to edit the Makefile when a new .cpp is added.
SRCS := $(sort $(shell find $(SRCDIR) -name '*.cpp'))

# src/core/Server.cpp -> obj/core/Server.o
OBJS := $(patsubst $(SRCDIR)/%.cpp,$(OBJDIR)/%.o,$(SRCS))

# One .d file per .o, generated by the compiler (see -MMD below).
DEPS := $(OBJS:.o=.d)

all: $(NAME)

$(NAME): $(OBJS)
	$(CXX) $(CXXFLAGS) $(OBJS) -o $@

$(OBJDIR)/%.o: $(SRCDIR)/%.cpp
	@mkdir -p $(dir $@)
	$(CXX) $(CXXFLAGS) -MMD -MP -I$(INCDIR) -c $< -o $@

clean:
	rm -rf $(OBJDIR)

fclean: clean
	rm -f $(NAME)

re:
	$(MAKE) fclean
	$(MAKE) all

.PHONY: all clean fclean re

# Pull in the header dependencies generated by -MMD.
# The leading '-' tells make to ignore the missing .d files on the first build.
-include $(DEPS)